#!/bin/bash
# download reference genome (if the server is not responding, please download them manually)
methrafo.download hg19 hg19

#predict based on provided MeDIP-Seq bam 
methrafo.bamScript example_medip.bam hg19/hg19.chrom.sizes
methrafo.predict hg19 example_medip.bam.sort.bam.bedGraph.sort.bw ../model/rr.pkl e1_out

# predict based on provided MeDIP-Seq bigwig 
methrafo.predict hg19 example_medip.bw ../model/rr.pkl e2_out
