language: python
python:
- '2.7'
sudo: true

before_install:
- pip install numpy
- pip install scipy
- pip install scikit-learn
- pip install pyBigWig
- sudo apt-get install samtools
- sudo apt-get install bedtools

script:
- python setup.py test
notifications:
  email: false
